# Tell appveyor to not use msbuild
build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.9
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.10
      MINICONDA: C:\Miniconda3

platform:
  - x86
  - x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION%"
  - activate test-environment
  - conda install numpy
  - conda install "scipy>=1.2"
  - pip install coverage


test_script:
  - cmd: python test.py
